### ISSUE TITLE
Efficient Way for Aggregate Call?

### ISSUE THREAD

**Issue by woozyking** [bitly/bitly-api-python#21]
Hi,

I went through the developer documentation, realized that there's no direct endpoints that provides aggregated information.

So I went ahead and used ThreadPool with a concurrency of 5 to try to improve sequential calls of all 11 endpoints I needed.

Here's the gist, let me know if there's any way to do it from the client side that could improve it!

https://gist.github.com/woozyking/4ad49ded84effdce6ef3

Or, please point me to the right documentation where there are aggregated endpoints :)

**Comment by jimmy927** [comment]
Is maybe this what you are looking for ?

https://github.com/jimmy927/bitly-api-python/pull/2

**Comment by woozyking** [comment]
Thanks @jimmy927 

It's been too long and I have no use for this client anymore.

Just glimpsed through the PR code change and realized that it's about `v3/bundle` API resource, and compared with my gist from back then, I would say it's not what I'm looking for. But I can't be sure and it's not that important any longer.
