### ISSUE TITLE
Set or edit tags using python client

### ISSUE THREAD

**Issue by rkpatel33** [bitly/bitly-api-python#44]
I notice that there does not seem to be a way to set the tag for links through the client, only bundles, yet from reading online bundles are deprecated.

Is there away to set/get tags using the API right now?

Thx.

**Comment by tpherndon** [comment]
There are no public APIs for dealing with tags right now, no.

**Comment by rkpatel33** [comment]
We will be creating thousands of shortened links for unique referral urls
to be sent in text messages. Is there any other way you suggestion to
organize them if they are create via API as part of a Django app?

My current fallback intention was to come up with a naming scheme that
would include all the info that I would need to look one up using the
search.

**Comment by tpherndon** [comment]
The normal recommendation for dealing with Bitlinks is to store, at the very least, the target URL and the Bitlink itself in a data store of some kind. That way you avoid re-shortening the same link, which wastes your rate limit, and you have a record of what you've done. When you need a Bitlink for a URL, look first in your data store. If you find the record, use that information. If you do not find a record, shorten the URL via the API, then store the result in your data store.

**Comment by rkpatel33** [comment]
Ok, thanks, that makes sense on our backend and will keep it in mind.

I was more asking about organizing in the web interface, since we will also
use the Bitly website to create manual PR and marketing links etc. Will be
hard to look at if it’s also cluttered with thousands of server generated
links as well.


_________________________
Rishi Patel | mail@rishinyc.com

**Comment by tpherndon** [comment]
Assuming you are a paying customer, I would separate your usage into two separate groups under the account, one for marketing and PR, and one for your automated referral Bitlinks.

**Comment by rkpatel33** [comment]
Awesome. Thx!
